openapi: 3.0.3
info:
  title: Xtream Codes API
  description: |
    Comprehensive API documentation for Xtream Codes IPTV Panel v2.9.2

    This API provides access to:
    - Live TV streams and categories
    - Video on Demand (VOD) content
    - TV Series with episodes
    - Electronic Program Guide (EPG)
    - User management and authentication
  version: 2.9.2
  contact:
    name: API Documentation
    url: https://github.com/worldofiptvcom/xtream-codes-api

servers:
  - url: http://{server}:{port}
    description: Xtream Codes Server
    variables:
      server:
        default: localhost
        description: Server hostname or IP
      port:
        default: "25461"
        description: Server port

tags:
  - name: Authentication
    description: User authentication and account info
  - name: Live TV
    description: Live TV streams and categories
  - name: VOD
    description: Video on Demand content
  - name: Series
    description: TV Series and episodes
  - name: EPG
    description: Electronic Program Guide

paths:
  /player_api.php:
    get:
      tags:
        - Authentication
      summary: Authenticate and get user info
      description: Authenticate user and retrieve account information
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: action
          in: query
          schema:
            type: string
            enum:
              - get_live_categories
              - get_live_streams
              - get_vod_categories
              - get_vod_streams
              - get_vod_info
              - get_series_categories
              - get_series
              - get_series_info
              - get_short_epg
              - get_simple_data_table
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'

  /player_api.php?action=get_live_categories:
    get:
      tags:
        - Live TV
      summary: Get live TV categories
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
      responses:
        '200':
          description: List of live TV categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /player_api.php?action=get_live_streams:
    get:
      tags:
        - Live TV
      summary: Get live TV streams
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: category_id
          in: query
          description: Filter by category ID
          schema:
            type: integer
      responses:
        '200':
          description: List of live streams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LiveStream'

  /player_api.php?action=get_vod_categories:
    get:
      tags:
        - VOD
      summary: Get VOD categories
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
      responses:
        '200':
          description: List of VOD categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /player_api.php?action=get_vod_streams:
    get:
      tags:
        - VOD
      summary: Get VOD streams
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: category_id
          in: query
          description: Filter by category ID
          schema:
            type: integer
      responses:
        '200':
          description: List of VOD streams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VodStream'

  /player_api.php?action=get_vod_info:
    get:
      tags:
        - VOD
      summary: Get VOD details
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: vod_id
          in: query
          required: true
          description: VOD stream ID
          schema:
            type: integer
      responses:
        '200':
          description: VOD information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VodInfo'

  /player_api.php?action=get_series_categories:
    get:
      tags:
        - Series
      summary: Get series categories
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
      responses:
        '200':
          description: List of series categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /player_api.php?action=get_series:
    get:
      tags:
        - Series
      summary: Get series list
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: category_id
          in: query
          description: Filter by category ID
          schema:
            type: integer
      responses:
        '200':
          description: List of series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Series'

  /player_api.php?action=get_series_info:
    get:
      tags:
        - Series
      summary: Get series details with episodes
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: series_id
          in: query
          required: true
          description: Series ID
          schema:
            type: integer
      responses:
        '200':
          description: Series information with episodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeriesInfo'

  /player_api.php?action=get_short_epg:
    get:
      tags:
        - EPG
      summary: Get short EPG for stream
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: stream_id
          in: query
          required: true
          description: Stream ID
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of programs to return
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: EPG listings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpgListings'

  /xmltv.php:
    get:
      tags:
        - EPG
      summary: Get full XMLTV EPG
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
      responses:
        '200':
          description: XMLTV format EPG
          content:
            application/xml:
              schema:
                type: string

  /get.php:
    get:
      tags:
        - Authentication
      summary: Get M3U playlist
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum: [m3u_plus, m3u]
        - name: output
          in: query
          schema:
            type: string
            enum: [ts, m3u8, rtmp]
      responses:
        '200':
          description: M3U playlist
          content:
            audio/x-mpegurl:
              schema:
                type: string

  /{username}/{password}/{stream_id}.ts:
    get:
      tags:
        - Live TV
      summary: Stream live TV (MPEG-TS)
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: password
          in: path
          required: true
          schema:
            type: string
        - name: stream_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Live stream
          content:
            video/mp2t:
              schema:
                type: string
                format: binary

  /movie/{username}/{password}/{stream_id}.mkv:
    get:
      tags:
        - VOD
      summary: Stream VOD content
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: password
          in: path
          required: true
          schema:
            type: string
        - name: stream_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: VOD stream
          content:
            video/x-matroska:
              schema:
                type: string
                format: binary

  /series/{username}/{password}/{episode_id}.mkv:
    get:
      tags:
        - Series
      summary: Stream series episode
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: password
          in: path
          required: true
          schema:
            type: string
        - name: episode_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Episode stream
          content:
            video/x-matroska:
              schema:
                type: string
                format: binary

components:
  parameters:
    username:
      name: username
      in: query
      required: true
      description: Account username
      schema:
        type: string
    password:
      name: password
      in: query
      required: true
      description: Account password
      schema:
        type: string

  schemas:
    UserInfo:
      type: object
      properties:
        user_info:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
            status:
              type: string
              enum: [Active, Banned, Disabled, Expired]
            exp_date:
              type: string
              nullable: true
            is_trial:
              type: string
            active_cons:
              type: string
            created_at:
              type: string
            max_connections:
              type: string
            allowed_output_formats:
              type: array
              items:
                type: string
        server_info:
          type: object
          properties:
            url:
              type: string
            port:
              type: string
            https_port:
              type: string
            server_protocol:
              type: string
            rtmp_port:
              type: string
            timezone:
              type: string
            timestamp_now:
              type: integer
            time_now:
              type: string

    Category:
      type: object
      properties:
        category_id:
          type: string
        category_name:
          type: string
        parent_id:
          type: integer

    LiveStream:
      type: object
      properties:
        num:
          type: integer
        name:
          type: string
        stream_type:
          type: string
        stream_id:
          type: integer
        stream_icon:
          type: string
        epg_channel_id:
          type: string
          nullable: true
        added:
          type: string
        category_id:
          type: string
        custom_sid:
          type: string
        tv_archive:
          type: integer
        direct_source:
          type: string
        tv_archive_duration:
          type: integer

    VodStream:
      type: object
      properties:
        num:
          type: integer
        name:
          type: string
        stream_type:
          type: string
        stream_id:
          type: integer
        stream_icon:
          type: string
        rating:
          type: string
        rating_5based:
          type: number
        added:
          type: string
        category_id:
          type: string
        container_extension:
          type: string
        custom_sid:
          type: string
        direct_source:
          type: string

    VodInfo:
      type: object
      properties:
        info:
          type: object
          properties:
            movie_image:
              type: string
            tmdb_id:
              type: string
            backdrop_path:
              type: array
              items:
                type: string
            youtube_trailer:
              type: string
            genre:
              type: string
            plot:
              type: string
            cast:
              type: string
            rating:
              type: string
            director:
              type: string
            releasedate:
              type: string
            duration_secs:
              type: integer
            duration:
              type: string
        movie_data:
          type: object
          properties:
            stream_id:
              type: integer
            name:
              type: string
            added:
              type: string
            category_id:
              type: string
            container_extension:
              type: string

    Series:
      type: object
      properties:
        num:
          type: integer
        name:
          type: string
        series_id:
          type: integer
        cover:
          type: string
        plot:
          type: string
        cast:
          type: string
        director:
          type: string
        genre:
          type: string
        releaseDate:
          type: string
        last_modified:
          type: string
        rating:
          type: string
        rating_5based:
          type: number
        backdrop_path:
          type: array
          items:
            type: string
        youtube_trailer:
          type: string
        episode_run_time:
          type: string
        category_id:
          type: string

    SeriesInfo:
      type: object
      properties:
        seasons:
          type: array
          items:
            type: object
            properties:
              season_number:
                type: integer
              name:
                type: string
              episode_count:
                type: integer
              cover:
                type: string
        info:
          type: object
          properties:
            name:
              type: string
            cover:
              type: string
            plot:
              type: string
            cast:
              type: string
            director:
              type: string
            genre:
              type: string
            releaseDate:
              type: string
            rating:
              type: string
        episodes:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                episode_num:
                  type: integer
                title:
                  type: string
                container_extension:
                  type: string
                info:
                  type: object
                  properties:
                    duration_secs:
                      type: integer
                    duration:
                      type: string
                    movie_image:
                      type: string
                    plot:
                      type: string
                    releasedate:
                      type: string

    EpgListings:
      type: object
      properties:
        epg_listings:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              epg_id:
                type: string
              title:
                type: string
              lang:
                type: string
              start:
                type: string
              end:
                type: string
              description:
                type: string
              channel_id:
                type: string
              start_timestamp:
                type: integer
              stop_timestamp:
                type: integer
